# -*- coding: utf-8 -*-
"""bess_LP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KpBm4Sq0UVwlG3vI0mQO4LUsKimCSEYq

## 1 · Load data
"""

import sys, subprocess
try:
    import pulp
except ImportError:
    subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q', 'pulp'])
    import pulp

import time
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

m = pd.read_csv('master_hourly.csv')
m['timestamp_jst'] = pd.to_datetime(m['timestamp_jst'])

print(f"Rows         : {len(m):,}  (expected 27,024)")
print(f"Columns      : {len(m.columns)}")
print(f"Time range   : {m['timestamp_jst'].min()}  ->  {m['timestamp_jst'].max()}")
print(f"\nColumns:")
print(list(m.columns))

"""## 2 · data quality summary

"""

print("=== Missing values ===")
nan_cols = [(c, m[c].isna().sum()) for c in m.columns if m[c].isna().sum() > 0]
if not nan_cols:
    print("  None.")
else:
    for c, n in nan_cols:
        print(f"  {c:<25s} {n:>4d}  ({n/len(m)*100:.2f}%)")

p = m['price_tokyo']
print(f"\n=== Price distribution (JPY/kWh) ===")
print(f"  Range          : {p.min():.2f} - {p.max():.2f}")
print(f"  Mean / Median  : {p.mean():.2f} / {p.median():.2f}")
print(f"  P90 / P95 / P99: {p.quantile(0.9):.2f} / {p.quantile(0.95):.2f} / {p.quantile(0.99):.2f}")
print(f"  Hours >= 50 JPY: {(p>=50).sum()}  ({(p>=50).mean()*100:.2f}%)")
print(f"  Hours >= 100 JPY: {(p>=100).sum()}")

print(f"\n=== Regime shift evidence ===")
h2_2022 = m[(m['timestamp_jst'] >= '2022-07-01') & (m['timestamp_jst'] < '2023-01-01')]
print(f"  2022 H2: median {h2_2022['price_tokyo'].median():.2f}  ·  hours >= 50 JPY: {(h2_2022['price_tokyo']>=50).sum()}")
for yr in [2023, 2024, 2025]:
    g = m[m['timestamp_jst'].dt.year == yr]
    print(f"  {yr}:    median {g['price_tokyo'].median():.2f}  ·  hours >= 50 JPY: {(g['price_tokyo']>=50).sum()}")

"""## 3 · EDA: price time series"""

plt.rcParams['figure.dpi'] = 110

fig, ax = plt.subplots(figsize=(13, 4.5))
ax.plot(m['timestamp_jst'], m['price_tokyo'], linewidth=0.3, color='#2E74B5', alpha=0.7)
m_monthly = m.set_index('timestamp_jst').resample('1ME')['price_tokyo'].mean()
ax.plot(m_monthly.index, m_monthly.values, linewidth=2, color='#C00000', label='Monthly mean')
ax.set_title('JEPX Tokyo Day-Ahead Price, Hourly (2022-06 to 2025-06)')
ax.set_ylabel('Price (JPY/kWh)')
ax.grid(True, alpha=0.3); ax.legend()
ax.xaxis.set_major_locator(mdates.MonthLocator(bymonth=[1, 7]))
ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m'))
plt.tight_layout()
plt.show()

"""## 4 · EDA: price distribution"""

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(13, 4.5))

ax1.hist(m['price_tokyo'], bins=100, color='#2E74B5', edgecolor='white', alpha=0.85)
ax1.set_yscale('log'); ax1.set_title('Price distribution (log scale)')
ax1.set_xlabel('Price (JPY/kWh)'); ax1.set_ylabel('Frequency (log)')
ax1.grid(True, alpha=0.3)

p_zoom = m[m['price_tokyo'] <= 50]['price_tokyo']
ax2.hist(p_zoom, bins=80, color='#70AD47', edgecolor='white', alpha=0.85)
ax2.set_title('Price distribution (zoomed <= 50 JPY/kWh)')
ax2.set_xlabel('Price (JPY/kWh)'); ax2.set_ylabel('Frequency')
ax2.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

"""## 5 · EDA: hourly boxplot (the duck-curve view)"""

fig, ax = plt.subplots(figsize=(13, 5))
data_by_hour = [m[m['hour'] == h]['price_tokyo'].values for h in range(24)]
bp = ax.boxplot(data_by_hour, tick_labels=list(range(24)),
                showfliers=True, patch_artist=True,
                flierprops={'markersize': 1, 'alpha': 0.3})
for patch in bp['boxes']:
    patch.set_facecolor('#9DC3E6'); patch.set_edgecolor('#2E74B5')
ax.set_title('Hourly Price Distribution by Hour of Day (JST)')
ax.set_xlabel('Hour of day'); ax.set_ylabel('Price (JPY/kWh)')
ax.set_ylim([0, 80]); ax.grid(True, alpha=0.3, axis='y')
plt.tight_layout()
plt.show()

"""## 6 · EDA: solar PV vs price"""

fig, ax = plt.subplots(figsize=(10, 6))
daytime = m[(m['hour'] >= 6) & (m['hour'] <= 18)].copy()
sc = ax.scatter(daytime['pv_actual'] / 1000, daytime['price_tokyo'],
                c=daytime['hour'], cmap='viridis', s=3, alpha=0.3)
ax.set_title('Solar PV Output vs JEPX Price (daytime 6-18)')
ax.set_xlabel('Solar PV generation (GW)')
ax.set_ylabel('JEPX Tokyo price (JPY/kWh)')
ax.set_ylim([0, 80])
plt.colorbar(sc, label='Hour of day')
ax.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

"""## 7 · EDA: LNG vs price (dual axis)"""

fig, ax1 = plt.subplots(figsize=(13, 5))
daily = m.set_index('timestamp_jst').resample('1D').agg({
    'price_tokyo': 'mean',
    'lng_japan_usd_mmbtu': 'first',
})
c1 = '#2E74B5'
ax1.plot(daily.index, daily['price_tokyo'], color=c1, linewidth=0.7, alpha=0.85)
ax1.set_ylabel('JEPX price (JPY/kWh, daily mean)', color=c1)
ax1.tick_params(axis='y', labelcolor=c1); ax1.grid(True, alpha=0.3)

ax2 = ax1.twinx()
c2 = '#C00000'
ax2.plot(daily.index, daily['lng_japan_usd_mmbtu'], color=c2, linewidth=2)
ax2.set_ylabel('LNG Japan ($/mmbtu)', color=c2)
ax2.tick_params(axis='y', labelcolor=c2)
plt.title('JEPX Daily Mean vs. Japan LNG Monthly')

ax1.xaxis.set_major_locator(mdates.MonthLocator(bymonth=[1, 7]))
ax1.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m'))
plt.tight_layout()
plt.show()

print("\nCorrelations with price_tokyo:")
for c in ['load', 'pv_actual', 'temp_c', 'lng_japan_usd_mmbtu']:
    print(f"  {c:<24s} {m[c].corr(m['price_tokyo']):.3f}")

"""## 8 · LP dispatch model

"""

# Battery parameters
P_MAX     = 10.0                  # MW
E_CAP     = 40.0                  # MWh (4-hour battery)
ETA_RT    = 0.85                  # round-trip efficiency
ETA_C     = np.sqrt(ETA_RT)       # ~0.9220 (charge leg)
ETA_D     = np.sqrt(ETA_RT)       # ~0.9220 (discharge leg)
SOC_MIN   = 0.10
SOC_MAX   = 0.90
SOC_FLOOR = SOC_MIN * E_CAP       # 4 MWh
SOC_CEIL  = SOC_MAX * E_CAP       # 36 MWh
USABLE    = SOC_CEIL - SOC_FLOOR  # 32 MWh
DT        = 1.0                   # hour
EPS       = 1e-4                  # tiny degeneracy penalty


def solve_day(prices_24, return_plan=True, verbose=False):
    """Solve one day's battery dispatch LP.

    Args:
        prices_24: iterable of 24 floats - hourly prices in JPY/kWh
        return_plan: if True, returns charge/discharge/SOC arrays
        verbose: solver messages on/off

    Returns:
        dict with: status, revenue_jpy, (optionally) charge, discharge, soc, prices
    """
    prices = np.asarray(prices_24, dtype=float)
    assert len(prices) == 24, f"Need 24 prices, got {len(prices)}"
    T = 24

    model = pulp.LpProblem("daily_arbitrage", pulp.LpMaximize)

    c = [pulp.LpVariable(f"c_{t}", lowBound=0, upBound=P_MAX) for t in range(T)]
    d = [pulp.LpVariable(f"d_{t}", lowBound=0, upBound=P_MAX) for t in range(T)]
    s = [pulp.LpVariable(f"s_{t}", lowBound=SOC_FLOOR, upBound=SOC_CEIL) for t in range(T)]

    # Objective in JPY: price [JPY/kWh] x MW x h x 1000 [kWh/MWh]
    revenue = pulp.lpSum(prices[t] * (d[t] - c[t]) * DT * 1000.0 for t in range(T))
    penalty = EPS * pulp.lpSum(c[t] + d[t] for t in range(T))
    model += revenue - penalty

    # SOC dynamics, starting empty (4 MWh)
    model += (s[0] == SOC_FLOOR + ETA_C * c[0] * DT - d[0] * DT / ETA_D), "soc_init"
    for t in range(1, T):
        model += (s[t] == s[t-1] + ETA_C * c[t] * DT - d[t] * DT / ETA_D), f"soc_{t}"

    # Diurnal closure
    model += (s[T-1] == SOC_FLOOR), "soc_closure"

    # One cycle per day (charge side)
    model += (pulp.lpSum(ETA_C * c[t] * DT for t in range(T)) <= USABLE), "one_cycle"

    solver = pulp.PULP_CBC_CMD(msg=1 if verbose else 0)
    status = model.solve(solver)

    if pulp.LpStatus[status] != 'Optimal':
        return {'status': pulp.LpStatus[status], 'revenue_jpy': np.nan}

    c_vals = np.array([c[t].varValue for t in range(T)])
    d_vals = np.array([d[t].varValue for t in range(T)])
    s_vals = np.array([s[t].varValue for t in range(T)])
    rev = float(np.sum(prices * (d_vals - c_vals) * DT) * 1000.0)

    out = {'status': 'Optimal', 'revenue_jpy': rev}
    if return_plan:
        out.update({'charge': c_vals, 'discharge': d_vals, 'soc': s_vals, 'prices': prices})
    return out

print("LP defined.")
print(f"  Power max        : {P_MAX} MW")
print(f"  Capacity         : {E_CAP} MWh")
print(f"  Round-trip eta   : {ETA_RT} (split as sqrt-eta on each leg = {ETA_C:.4f})")
print(f"  SOC bounds       : [{SOC_FLOOR}, {SOC_CEIL}] MWh")
print(f"  Usable per cycle : {USABLE} MWh")

"""## 9 · LP validation — 3 hand-calculable cases

"""

# --- Case 1: 12h @ 0 + 12h @ 100 JPY/kWh ---
print("=" * 70)
print("CASE 1: 12h @ 0 JPY  +  12h @ 100 JPY")
print("=" * 70)
prices1 = np.array([0.0]*12 + [100.0]*12)
r1 = solve_day(prices1)
expected1 = USABLE * ETA_D * 100 * 1000   # ~2,950,000
print(f"  Revenue          : {r1['revenue_jpy']:>14,.2f} JPY")
print(f"  Expected         : {expected1:>14,.2f} JPY")
print(f"  Implied RTE      : {r1['discharge'].sum()/r1['charge'].sum()*100:.2f} %")
assert abs(r1['revenue_jpy'] - expected1) < 500, "CASE 1 FAILED"
print("  PASS\n")

# --- Case 2: flat prices -> no arbitrage ---
print("=" * 70)
print("CASE 2: Flat 15 JPY all day - should be zero revenue")
print("=" * 70)
r2 = solve_day(np.full(24, 15.0))
print(f"  Revenue          : {r2['revenue_jpy']:>14,.4f} JPY  (expected 0)")
assert abs(r2['revenue_jpy']) < 1.0, "CASE 2 FAILED"
print("  PASS\n")

# --- Case 3: two arbitrage windows; LP must pick the larger spread ---
print("=" * 70)
print("CASE 3: Two arbitrage windows - LP must pick the larger spread")
print("=" * 70)
prices3 = np.array([5]*6 + [50]*6 + [3]*6 + [80]*6, dtype=float)
r3 = solve_day(prices3)
expected3 = (USABLE * ETA_D) * 80 * 1000 - (USABLE / ETA_C) * 3 * 1000
print(f"  Revenue          : {r3['revenue_jpy']:>14,.2f} JPY")
print(f"  Expected         : {expected3:>14,.2f} JPY")
print(f"  Charge in cheap-A: {r3['charge'][0:6].sum():.3f} MWh  (should ~ 0)")
print(f"  Charge in cheap-B: {r3['charge'][12:18].sum():.3f} MWh")
assert abs(r3['revenue_jpy'] - expected3) < 500, "CASE 3 FAILED"
print("  PASS\n")

print("All 3 sanity checks PASSED. LP validated.")

"""## 10 · Perfect-foresight benchmark (1,126 days)

"""

m['date'] = m['timestamp_jst'].dt.tz_localize(None).dt.date
daily = m.groupby('date')
dates = sorted(daily.groups.keys())
print(f"Days to solve: {len(dates):,}")

records = []
t0 = time.time()
for i, d in enumerate(dates):
    g = daily.get_group(d).sort_values('timestamp_jst')
    prices = g['price_tokyo'].values
    r = solve_day(prices, return_plan=True)
    if r['status'] != 'Optimal':
        records.append({'date': d, 'revenue_jpy': np.nan})
        continue
    records.append({
        'date'        : d,
        'revenue_jpy' : r['revenue_jpy'],
        'max_price'   : float(prices.max()),
        'min_price'   : float(prices.min()),
        'mean_price'  : float(prices.mean()),
        'spread'      : float(prices.max() - prices.min()),
    })
    if (i + 1) % 200 == 0:
        print(f"  {i+1:>4d}/{len(dates)}  elapsed={time.time()-t0:.1f}s")

dt_total = time.time() - t0
print(f"\nSolved {len(records)} days in {dt_total:.1f}s ({dt_total/len(records)*1000:.1f} ms/day)")

pf = pd.DataFrame(records)
pf['date'] = pd.to_datetime(pf['date'])
pf = pf.sort_values('date').reset_index(drop=True)
pf['revenue_cum'] = pf['revenue_jpy'].cumsum()
pf['year'] = pf['date'].dt.year

print("\n=== Annual perfect-foresight summary ===")
yearly = pf.groupby('year').agg(
    days=('revenue_jpy', 'size'),
    total_jpy=('revenue_jpy', 'sum'),
    mean_daily_jpy=('revenue_jpy', 'mean'),
    max_daily_jpy=('revenue_jpy', 'max'),
).round(0).astype({'days': int})
print(yearly.to_string())

total = pf['revenue_jpy'].sum()
all_2022 = pf[pf['date'] < '2023-01-01']['revenue_jpy'].sum()
print(f"\nTotal 3-year PF revenue : ¥{total:,.0f}  ({total/1e6:.1f} M)")
print(f"2022 contribution       : ¥{all_2022:,.0f}  ({all_2022/total*100:.1f}%)  <- '46% from 2022' on slide 8")

pf.to_csv('pf_daily_revenue.csv', index=False)
print(f"\nSaved: pf_daily_revenue.csv")

"""## 11 · Cumulative PF revenue curve

"""

fig, ax = plt.subplots(figsize=(11, 5), dpi=120)

ax.plot(pf['date'], pf['revenue_cum'] / 1e6, color='#1F3864', linewidth=2.0)
ax.fill_between(pf['date'], 0, pf['revenue_cum'] / 1e6, color='#1F3864', alpha=0.12)

ye = pf.groupby(pf['date'].dt.year).tail(1)
for _, row in ye.iterrows():
    ax.annotate(f"¥{row['revenue_cum']/1e6:.0f}M",
                xy=(row['date'], row['revenue_cum']/1e6),
                xytext=(6, 0), textcoords='offset points',
                fontsize=10, color='#1F3864', va='center', fontweight='bold')

end_2022 = pf[pf['date'] == '2022-12-31'].iloc[0]
ax.scatter([end_2022['date']], [end_2022['revenue_cum']/1e6],
           color='#C00000', s=70, zorder=5, edgecolor='white', linewidth=1.5)
ax.annotate(f"End of 2022\n¥{end_2022['revenue_cum']/1e6:.0f}M ({end_2022['revenue_cum']/total*100:.0f}% of 3-year PF)",
            xy=(end_2022['date'], end_2022['revenue_cum']/1e6),
            xytext=(20, -35), textcoords='offset points',
            fontsize=10, color='#C00000', fontweight='bold',
            bbox=dict(boxstyle='round,pad=0.35', facecolor='#FFF4F4',
                      edgecolor='#C00000', linewidth=0.8),
            arrowprops=dict(arrowstyle='->', color='#C00000', lw=0.8))

ax.set_ylabel('Cumulative PF revenue (M JPY)')
ax.set_title('Perfect-Foresight Cumulative Revenue (10 MW / 40 MWh, 85% RTE, 1 cycle/day)')
ax.grid(True, alpha=0.3)
ax.spines['top'].set_visible(False); ax.spines['right'].set_visible(False)
ax.xaxis.set_major_locator(mdates.MonthLocator(bymonth=[1, 7]))
ax.xaxis.set_major_formatter(mdates.DateFormatter('%b %Y'))
ax.set_xlim(pf['date'].min(), pf['date'].max() + pd.Timedelta(days=30))
ax.set_ylim(0, pf['revenue_cum'].max()/1e6 * 1.08)

plt.tight_layout()
plt.show()

"""## 12 · Naive fixed-schedule baseline (lower bound)

"""

# Naive fixed schedule
CHARGE_HOURS = [10, 11, 12, 13]    # 10am-2pm
DISCHARGE_HOURS = [17, 18, 19, 20] # 5pm-9pm

# Energy-balanced rates: charge at 8 MW, discharge at 8 x eta = 6.8 MW
# (so what we charge in equals what we draw out, given round-trip loss)
C_RATE = 8.0                # MW charging
D_RATE = C_RATE * ETA_RT    # ~6.8 MW discharging

# Build hourly charge/discharge pattern
charge_pat = np.zeros(24)
discharge_pat = np.zeros(24)
for h in CHARGE_HOURS: charge_pat[h] = C_RATE
for h in DISCHARGE_HOURS: discharge_pat[h] = D_RATE

print(f"Naive schedule:")
print(f"  Charge   {CHARGE_HOURS} at {C_RATE} MW = {C_RATE * len(CHARGE_HOURS):.1f} MWh charged")
print(f"  Discharge {DISCHARGE_HOURS} at {D_RATE:.2f} MW = {D_RATE * len(DISCHARGE_HOURS):.1f} MWh delivered")

# Compute revenue per day under the fixed schedule
naive_records = []
for d_, g in m.groupby('date'):
    g = g.sort_values('timestamp_jst')
    if len(g) != 24: continue
    prices = g['price_tokyo'].values
    rev = float(np.sum(prices * (discharge_pat - charge_pat)) * 1000)
    naive_records.append({'date': d_, 'naive_rev': rev})

naive_df = pd.DataFrame(naive_records)
naive_df['date'] = pd.to_datetime(naive_df['date'])

naive_total = naive_df['naive_rev'].sum()
naive_neg_days = (naive_df['naive_rev'] < 0).sum()

print(f"\n=== Naive baseline results ===")
print(f"  Total over 3 years : ¥{naive_total:,.0f}  ({naive_total/1e6:.1f} M)")
print(f"  Mean per day       : ¥{naive_df['naive_rev'].mean():,.0f}")
print(f"  Days losing money  : {naive_neg_days} / {len(naive_df)}  ({naive_neg_days/len(naive_df)*100:.1f}%)")

"""## 13 · naive vs PF

"""

combined = pf.merge(naive_df, on='date')

pf_total = combined['revenue_jpy'].sum()
naive_total = combined['naive_rev'].sum()
headroom = pf_total - naive_total

print("=== HEADLINE COMPARISON ===")
print(f"  Naive baseline (fixed)   : ¥{naive_total/1e6:.1f}M  ({naive_total/pf_total*100:.1f}% of PF)")
print(f"  PF upper bound (perfect) : ¥{pf_total/1e6:.1f}M  (100%)")
print(f"  Headroom for forecasts   : ¥{headroom/1e6:.1f}M  ({headroom/pf_total*100:.1f}%)")

print(f"\n=== Annual breakdown ===")
combined['year'] = combined['date'].dt.year
yearly = combined.groupby('year').agg(
    days=('date', 'count'),
    pf_M=('revenue_jpy', lambda x: x.sum()/1e6),
    naive_M=('naive_rev', lambda x: x.sum()/1e6),
).round(2)
yearly['naive_pct_of_pf'] = (yearly['naive_M'] / yearly['pf_M'] * 100).round(1)
print(yearly.to_string())

print(f"\nNote: in 2022 the spike regime makes the fixed schedule miss most of the value")
print(f"      (naive captures only {yearly.loc[2022, 'naive_pct_of_pf']:.0f}% of PF in 2022),")
print(f"      while in calm years it captures more (~50-60% of PF).")

"""## 14 · Visualizing both bounds"""

combined = combined.sort_values('date').reset_index(drop=True)
combined['pf_cum'] = combined['revenue_jpy'].cumsum() / 1e6
combined['naive_cum'] = combined['naive_rev'].cumsum() / 1e6

fig, ax = plt.subplots(figsize=(11, 5), dpi=120)

ax.fill_between(combined['date'], 0, combined['naive_cum'], color='#9DC3E6', alpha=0.5, label='Naive (no forecast)')
ax.fill_between(combined['date'], combined['naive_cum'], combined['pf_cum'], color='#1F3864', alpha=0.25, label='Headroom for forecasts')
ax.plot(combined['date'], combined['pf_cum'], color='#1F3864', linewidth=2.0, label='PF (perfect foresight)')
ax.plot(combined['date'], combined['naive_cum'], color='#5B6E8C', linewidth=1.5, linestyle='--')

ax.annotate(f"PF: ¥{combined['pf_cum'].iloc[-1]:.0f}M",
            xy=(combined['date'].iloc[-1], combined['pf_cum'].iloc[-1]),
            xytext=(8, 2), textcoords='offset points',
            color='#1F3864', fontweight='bold', fontsize=11)
ax.annotate(f"Naive: ¥{combined['naive_cum'].iloc[-1]:.0f}M ({combined['naive_cum'].iloc[-1]/combined['pf_cum'].iloc[-1]*100:.0f}% of PF)",
            xy=(combined['date'].iloc[-1], combined['naive_cum'].iloc[-1]),
            xytext=(8, 0), textcoords='offset points',
            color='#5B6E8C', fontsize=10)

ax.set_ylabel('Cumulative revenue (M JPY)')
ax.set_title('Cumulative revenue: PF ceiling vs naive baseline floor')
ax.grid(True, alpha=0.3)
ax.spines['top'].set_visible(False); ax.spines['right'].set_visible(False)
ax.legend(loc='upper left', frameon=False)
ax.xaxis.set_major_locator(mdates.MonthLocator(bymonth=[1, 7]))
ax.xaxis.set_major_formatter(mdates.DateFormatter('%b %Y'))
ax.set_xlim(combined['date'].min(), combined['date'].max() + pd.Timedelta(days=180))
ax.set_ylim(0, combined['pf_cum'].max() * 1.08)

plt.tight_layout()
plt.show()